### PR TITLE
Adding settings.jar for others to import

### PR DESCRIPTION
**Pull request by donovamb**
```
* The jar file has 3 things exported:
    - The code style as defined by the krush-android-style-guide
    - The Macro I use to overwrite command + s to format and save
    - The file template to add a TODO in the class java doc rather
      than the name of the creator
```

---

This change is [Reviewable](https://reviewable.io/reviews/krushtech/style-guide/2)

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/krushtech/style-guide/pull/2" target="_blank">ReviewNinja

**Comment by dvanwinkle** [comment]
!fix rebase

**Comment by donovamb** [comment]
!fixed

**Comment by kprenger** [comment]
!starred

**Comment by bbeverl** [comment]
!star

**Comment by matthewsparr** [comment]
!star

**Comment by kprenger** [comment]
!starred

**Comment by kprenger** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/krushtech/style-guide/2#-:-KRF2rW_k5Tay_x1P6jH:bnfp4nl)*

**Pull request merged**
