### PR TITLE
Create Android.gitignore

### PR DESCRIPTION
**Pull request by benbeverly**
For a default we bring into new projects. Let's edit and add on.
I started with the standard from Github.com and added .DS_STORE and Thumbs.db

---

This change is [Reviewable](https://reviewable.io/reviews/krushtech/style-guide/4)

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/krushtech/style-guide/pull/4" target="_blank">ReviewNinja

**Comment by kprenger** [comment]
!starred

**Comment by matthewsparr** [comment]
!star

**Comment by kprenger** [comment]
!starred

**Comment by kprenger** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/krushtech/style-guide/4#-:-KRF2w2dhF_w0iRX1yUa:bnfp4nl)*

**Comment by kprenger** [comment]
!star

**Comment by donovamb** [comment]
May be worth adding ".bundle" and "vendor" for bundler installs. most of the projects have it in their .gitignore anyway.

**Comment by benbeverly** [comment]
@donovamb Are those directories or files?

**Comment by dvanwinkle** [comment]
!star

**Pull request merged**
